; PlatformIO Project Configuration File - Shout Booth
; Two environments: controller (ESP32) and listener (ESP32-C3 + INMP441)

[platformio]
default_envs = controller, listener

[env:controller]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<controller/>

[env:listener]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<listener/>
